/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.bbs.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-19-2010
 * 
 * XDoclet definition:
 * @struts.form name="editTopicForm"
 */
public class EditPostsForm extends ActionForm {
	/*
	 * Generated fields
	 */
    private String pages;
    
	/** replyid property */
	private String replyid;

	/** topicid property */
	private String topicid;

	/** topicContent property */
	private String topicContent;

	/** author property */
	private String author;
	
	/** author property */
	private String replyAuthor;
	
	/** topicSign property */
	private String topicSign;
	
	/** opration property */
	private String opration;
	
	/** sectionId property */
	private String sectionId ;
	
	private String userId;
	
	private String topicTopic;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the replyid.
	 * @return String
	 */
	public String getReplyid() {
		return replyid;
	}

	/** 
	 * Set the replyid.
	 * @param replyid The replyid to set
	 */
	public void setReplyid(String replyid) {
		this.replyid = replyid;
	}

	/** 
	 * Returns the topicid.
	 * @return String
	 */
	public String getTopicid() {
		return topicid;
	}

	/** 
	 * Set the topicid.
	 * @param topicid The topicid to set
	 */
	public void setTopicid(String topicid) {
		this.topicid = topicid;
	}

	/** 
	 * Returns the topicContent.
	 * @return String
	 */
	public String getTopicContent() {
		return topicContent;
	}

	/** 
	 * Set the topicContent.
	 * @param topicContent The topicContent to set
	 */
	public void setTopicContent(String topicContent) {
		this.topicContent = topicContent;
	}

	/** 
	 * Returns the author.
	 * @return String
	 */
	public String getAuthor() {
		return author;
	}

	/** 
	 * Set the author.
	 * @param author The author to set
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * @return the topicSign
	 */
	public String getTopicSign() {
		return topicSign;
	}

	/**
	 * @param topicSign the topicSign to set
	 */
	public void setTopicSign(String topicSign) {
		this.topicSign = topicSign;
	}

	/**
	 * @return the pages
	 */
	public String getPages() {
		return pages;
	}

	/**
	 * @param pages the pages to set
	 */
	public void setPages(String pages) {
		this.pages = pages;
	}

	/**
	 * @return the opration
	 */
	public String getOpration() {
		return opration;
	}

	/**
	 * @param opration the opration to set
	 */
	public void setOpration(String opration) {
		this.opration = opration;
	}

	/**
	 * @return the sectionId
	 */
	public String getSectionId() {
		return sectionId;
	}

	/**
	 * @param sectionId the sectionId to set
	 */
	public void setSectionId(String sectionId) {
		this.sectionId = sectionId;
	}

	/**
	 * @return the userId
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * @return the topicTopic
	 */
	public String getTopicTopic() {
		return topicTopic;
	}

	/**
	 * @param topicTopic the topicTopic to set
	 */
	public void setTopicTopic(String topicTopic) {
		this.topicTopic = topicTopic;
	}

	/**
	 * @return the replyAuthor
	 */
	public String getReplyAuthor() {
		return replyAuthor;
	}

	/**
	 * @param replyAuthor the replyAuthor to set
	 */
	public void setReplyAuthor(String replyAuthor) {
		this.replyAuthor = replyAuthor;
	}
}