/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.bbs.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors; 
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 08-22-2008
 * 
 * XDoclet definition:
 * @struts.form name="userForm"
 */
public class UserForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** fileName property */
	private String fileName;
	
	/** image property */
	private FormFile image;
	
	private int userId;
	
	private String userName;
	
	private String userPassword;
	
	private String userNName;
	
	private String userSex;
	
	private String userEmail;
	
	private String userRegDate;
	
	private int userClass;
	
	private int  userPoint;
	
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
//		ActionErrors errors=new ActionErrors();
//			if(userNName==null||userNName.equals("")){
//				errors.add("userNName", new ActionError("请输入合法的用户昵称"));
//			}
//		
//		return errors;
		return null;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return fileName;
	}
	/**
	 * @param fileName the fileName to set
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	/**
	 * @return the image
	 */
	public FormFile getImage() {
		return image;
	}
	/**
	 * @param image the image to set
	 */
	public void setImage(FormFile image) {
		this.image = image;
	}
	/**
	 * @return the userNName
	 */
	public String getUserNName() {
		return userNName;
	}
	/**
	 * @param userNName the userNName to set
	 */
	public void setUserNName(String userNName) {
		this.userNName = userNName;
	}

	/**
	 * @return the userId
	 */
	public int getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the userPassword
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * @param userPassword the userPassword to set
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * @return the userSex
	 */
	public String getUserSex() {
		return userSex;
	}

	/**
	 * @param userSex the userSex to set
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/**
	 * @return the userEmail
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * @param userEmail the userEmail to set
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * @return the userRegDate
	 */
	public String getUserRegDate() {
		return userRegDate;
	}

	/**
	 * @param userRegDate the userRegDate to set
	 */
	public void setUserRegDate(String userRegDate) {
		this.userRegDate = userRegDate;
	}

	/**
	 * @return the userClass
	 */
	public int getUserClass() {
		return userClass;
	}

	/**
	 * @param userClass the userClass to set
	 */
	public void setUserClass(int userClass) {
		this.userClass = userClass;
	}

	/**
	 * @return the userPoint
	 */
	public int getUserPoint() {
		return userPoint;
	}

	/**
	 * @param userPoint the userPoint to set
	 */
	public void setUserPoint(int userPoint) {
		this.userPoint = userPoint;
	}
	
	
	
}