/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class SaveTokenAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			String path = request.getParameter("path");
			saveToken(request);
			if(path!=null&&!path.equals("")) {
				if(path.equals("post")){
				    request.setAttribute("id", request.getParameter("id"));
				}
				if(path.equals("reply")){
				   request.setAttribute("topic", request.getParameter("topic").trim());
				   request.setAttribute("topicid", request.getParameter("topicid"));
				   request.setAttribute("author", request.getParameter("author"));
				}
				return mapping.findForward(path);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			return mapping.findForward("error");
		}
		
		return null;
	}
}