/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.manage.control.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-04-2010
 * 
 * XDoclet definition:
 * @struts.form name="addBunUserForm"
 */
public class AddBunUserForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** delpost property */
	private String delpost;

	/** type property */
	private String type;

	/** username property */
	private String username;

	/** bantime property */
	private String bunOverTime;

	/** bunReason property */
	private String bunReason;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the delpost.
	 * @return String
	 */
	public String getDelpost() {
		return delpost;
	}

	/** 
	 * Set the delpost.
	 * @param delpost The delpost to set
	 */
	public void setDelpost(String delpost) {
		this.delpost = delpost;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the bunReason.
	 * @return String
	 */
	public String getBunReason() {
		return bunReason;
	}

	/** 
	 * Set the bunReason.
	 * @param bunReason The bunReason to set
	 */
	public void setBunReason(String bunReason) {
		this.bunReason = bunReason;
	}

	/**
	 * @return the bunBeginTime
	 */
	public String getBunOverTime() {
		return bunOverTime;
	}

	/**
	 * @param bunBeginTime the bunBeginTime to set
	 */
	public void setBunOverTime(String bunBeginTime) {
		this.bunOverTime = bunBeginTime;
	}
}