/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.manage.control.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-25-2010
 * 
 * XDoclet definition:
 * @struts.form name="topicInfoForm"
 */
public class TopicInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** section property */
	private String section;

	/** title property */
	private String title;

	/** topiccontent property */
	private String topiccontent;

	/** username property */
	private String username;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the section.
	 * @return String
	 */
	public String getSection() {
		return section;
	}

	/** 
	 * Set the section.
	 * @param section The section to set
	 */
	public void setSection(String section) {
		this.section = section;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the topiccontent.
	 * @return String
	 */
	public String getTopiccontent() {
		return topiccontent;
	}

	/** 
	 * Set the topiccontent.
	 * @param topiccontent The topiccontent to set
	 */
	public void setTopiccontent(String topiccontent) {
		this.topiccontent = topiccontent;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}