/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.manage.control.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.itstar.manage.dbconnection.DBConnection;
import com.itstar.manage.control.form.AddSectionForm;
import com.itstar.dao.SectionDao;
/**
 * MyEclipse Struts Creation date: 08-24-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AddSectionAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		 AddSectionForm  addSectionForm = (AddSectionForm)form;
		 SectionDao dao = new SectionDao();
		 boolean bl = false;
		//判断是否是重复提交
		if(isTokenValid(request, true)){
			bl = dao.addSection(addSectionForm);
			if(bl=true){;
				request.setAttribute("message", "sectionSuccess");
			} else {
			    request.setAttribute("message", "sectionError");
			}
			saveToken(request);
			return mapping.findForward("point");		
		} else{
			resetToken(request);
			request.setAttribute("error", "重复提交");
			return mapping.findForward("error");
	     }
		
	}
}