/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.manage.control.action;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.itstar.dao.PostsDao;
import com.itstar.manage.control.form.DeletePostsForm;
import com.itstar.manage.dbconnection.DatabaseConnection;
import com.itstar.model.BBSPosts;
import com.itstar.util.Page;

public class DeletePostsAction extends DispatchAction  {
	
	/**
	 * 定义前台是否显示详细列表信息的参数 0只搜索显示记录总数 1显示记录数，2显示列表
	 */
	
	/*
	 * Generated Methods
	 */

	/** 显示主题帖子及回帖
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		DeletePostsForm deletePostsForm = (DeletePostsForm) form;// TODO Auto-generated method stub
		request.setCharacterEncoding("GBK");
		response.setCharacterEncoding("GBK");	
		// 定义如下分页变量
		// 2、定义一个当前是第几页
		int currentPage = 1;
		Page page =null;
		int resultState = 0; 
		//获取form 属性值
		String content = deletePostsForm.getPostsContent();
		String author = deletePostsForm.getAuthor();
		String section = deletePostsForm.getSection();
		ArrayList<BBSPosts> array = new ArrayList<BBSPosts>();
		
		// 接收传过来的当前页
		try {
			if(request.getParameter("cp")!=null && !request.getParameter("cp").equals("")) {
				   currentPage = Integer.parseInt(request.getParameter("cp"));
			}
		
		//接收前台是否显示详细列表信息的参数值
		if(request.getParameter("resultState")!=null) {
		   resultState = Integer.parseInt(request.getParameter("resultState"));
		}
		
		PostsDao dao = new PostsDao();
		//获取列表值
		array = dao.getPostsArray(deletePostsForm);
		//分页
		page = new Page(array,String.valueOf(currentPage));
		
		request.getSession().setAttribute("postslist", Page.relist);
		request.setAttribute("array", Page.relist);
		request.setAttribute("currentPage", currentPage);
		request.setAttribute("resultState", resultState);
		request.setAttribute("pageSize", Page.allpage);
		request.setAttribute("allRecorders", Page.allCol);
		request.setAttribute("form", deletePostsForm);
		//request.setAttribute("sectionName", section);
		//request.setAttribute("author", author);
} catch (Exception e) {
			e.printStackTrace();
		}
		return mapping.findForward("show");
	}
	
	/**
	 * 删除主题帖子及回复
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		PostsDao dao = new PostsDao();
		HttpSession session = request.getSession();
		//取得帖子的list编号
		String id = request.getParameter("id"); 
		//是否显示详细列表
		int resultState = 0;
		//取得帖子的list列表
		ArrayList<BBSPosts> list = (ArrayList<BBSPosts>)session.getAttribute("postslist");
		for(int i = 0; i < id.split(",").length; i++) {
			String str = id.split(",")[i];
			dao.deletePosts(str, list);
		}
		if(request.getParameter("resultState")!=null) {
			   resultState = Integer.parseInt(request.getParameter("resultState"));
			}
		request.setAttribute("resultState", resultState);
		return mapping.findForward("deleteposts");
	}
	
}