/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.manage.control.action;
import java.util.List;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.itstar.dao.TopicDao;
import com.itstar.dao.UserDao;
import com.itstar.manage.control.form.TopicInfoForm;
import com.itstar.manage.dbconnection.DatabaseConnection;
import com.itstar.model.BBSTopic;
import com.itstar.util.Page;

public class DisplayTopicAction extends DispatchAction {
	
	
	
	/**
	 * Method show
	 * 查看主题帖子列表信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception
	 */
	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		TopicInfoForm topicForm = (TopicInfoForm)form;
		request.setCharacterEncoding("GBK");
		response.setCharacterEncoding("GBK");	
		int resultState=0; //是否显示详细信息 0不显示 1显示
		// 定义如下分页变量
		String currentPage = "1";
		Page page =null;
		// 接收传过来的当前页
		try {
			if(request.getParameter("cp")!=null && !request.getParameter("cp").equals("")) {
			   currentPage = request.getParameter("cp");
			}
			if(request.getParameter("resultState")!=null) {
				   resultState = Integer.parseInt(request.getParameter("resultState"));
			}
			
		} catch (Exception e) {
			
		}
		
		// 获取总记录数
		
		// 获取信息列表
		TopicDao topicDao  = new TopicDao();
	    List<BBSTopic>  array = topicDao.getArray(topicForm);
	    page = new Page(array,currentPage);
		request.setAttribute("array", Page.relist);
		request.setAttribute("currentPage", currentPage);
		request.setAttribute("resultState", resultState);
		request.setAttribute("pageSize", Page.allpage);
		request.setAttribute("allRecorders", Page.allCol);
		request.setAttribute("form", topicForm);
		return mapping.findForward("showTopic");
	}
	/**
	 * 删除主题帖子
	 * Method delete
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		int resultState=0; //是否显示详细信息 0不显示 1显示
		String id = request.getParameter("id");//取得帖子号
		TopicDao topicDao  = new TopicDao();
		topicDao.deleteTopic(id);
		if(request.getParameter("resultState")!=null) {
			   resultState = Integer.parseInt(request.getParameter("resultState"));
			}
		request.setAttribute("resultState", resultState);
		return mapping.findForward("update");
	}
	
	/**
	 * 置顶主题帖子
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward top(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		int resultState=0; //是否显示详细信息 0不显示 1显示
		String id = request.getParameter("id");//取得帖子号
		TopicDao topicDao  = new TopicDao();
		topicDao.toptopic(id);
		if(request.getParameter("resultState")!=null) {
			   resultState = Integer.parseInt(request.getParameter("resultState"));
			}
		request.setAttribute("resultState", resultState);
		return mapping.findForward("update");
	}
	
	/**
	 * 精华主题帖子
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward state(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		String id = request.getParameter("id");//取得帖子号
		int resultState=0; //是否显示详细信息 0不显示 1显示
		TopicDao topicDao  = new TopicDao();
		topicDao.statetopic(id);
		if(request.getParameter("resultState")!=null) {
			   resultState = Integer.parseInt(request.getParameter("resultState"));
		}
		request.setAttribute("resultState", resultState);
		return mapping.findForward("update");
	}
	
	/**
	 * 查看主题帖子
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		String id = request.getParameter("id");//取得帖子号
		int resultState=0; //是否显示详细信息 0不显示 1显示
		TopicDao topicDao  = new TopicDao();
		BBSTopic topic = topicDao.getBBSTopic(id);
		UserDao udao2 = new UserDao();
		try {
			Map usermap = udao2.getUserMap();
			
			topic.setUserName((String)usermap.get(topic.getTopicUserId()));
			
			request.setAttribute("topic",topic);
			if(request.getParameter("resultState")!=null) {
				   resultState = Integer.parseInt(request.getParameter("resultState"));
			}
			request.setAttribute("resultState", resultState);
		} catch (RuntimeException e) {
			e.printStackTrace();
		}
		return mapping.findForward("view");
	}
	
}