/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.itstar.manage.control.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.itstar.dao.PasswordDao;
import com.itstar.model.BBSPassword;
import com.itstar.util.Page;

public class FindPasswordManageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method show
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String userName = request.getParameter("userName");
		// 定义如下分页变量
		String currentPage = "1";
		Page page = null;
		// 接收传过来的当前页
		try {
			if (request.getParameter("cp") != null
					&& !request.getParameter("cp").equals("")) {
				currentPage = request.getParameter("cp");
			}
		} catch (Exception e) {

		}
		try {
			PasswordDao pdao = new PasswordDao();
			ArrayList<BBSPassword> list = new ArrayList<BBSPassword>();
			if (userName == null || userName.equals("")) {
				list = pdao.getFindPassword();
			} else {
				list = pdao.getFindPasswordByName(userName);
			}
			page = new Page(list, String.valueOf(currentPage));

			request.setAttribute("array", Page.relist);
			request.setAttribute("currentPage", currentPage);
			request.setAttribute("pageSize", Page.allpage);
			request.setAttribute("allRecorders", Page.allCol);
			request.setAttribute("array", Page.relist);
		} catch (RuntimeException e) {
			
			// TODO Auto-generated catch block
			e.printStackTrace();
			
		}
		return mapping.findForward("findPassword");
	}
	
   /**
    * 重设密码
    * @param mapping
    * @param form
    * @param request
    * @param response
    * @return
    */
	public ActionForward reset(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//
		try {
			PrintWriter out = response.getWriter();
			PasswordDao pdao = new PasswordDao();
			String passwordId = request.getParameter("passwordId");
			pdao.setUserPassword(passwordId);
			out.print(passwordId);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
	
    /**
     * 删除
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return
     */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PasswordDao pdao = new PasswordDao();
		String passwordId = request.getParameter("passwordId");
		pdao.deleteFindPassword(passwordId);
		return mapping.findForward("delete");
	}
}